#!/usr/bin/exec-suid --real -- /usr/bin/python -I
# -*- mode: python -*-
import sys
from getpass import getpass
sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            return f.read()
    except FileNotFoundError:
        print("Error: Flag file not found.")

def main():
    if sys.argv[0] == 'ssh' and sys.argv[1] == 'hacker@coolmachine':
        if getpass("hacker@coolmachine's password: ") == 'Password1!':
            print(f"Congratulations! You have successfully logged in to coolmachine as the user 'hacker'. Here is your flag:")
            print(print_flag())

if __name__ == '__main__':
    main()
