#!/usr/bin/python3.12
# -*- mode: python -*-
import sys
from getpass import getpass
sys.path.append('/challenge')

def main():
    if sys.argv[0] == 'ssh' and sys.argv[1] == 'hacker@coolmachine':
        if getpass("hacker@coolmachine's password: ") == 'Password1!':
            with open('/tmp/ran', 'w') as f:
                f.write('ran')
            print(f"Congratulations! You have successfully logged in to coolmachine as the user 'hacker'.")
            print("Run /challenge/solve again to get your flag.")
    else:
        print("ssh: no route to host")

if __name__ == '__main__':
    main()
