#!/usr/bin/exec-suid -- /usr/bin/python3.12 -I
from os import path
import sys
sys.path.append('/challenge')

def setup():
    with open("/tmp/searchme", "w") as f:
        f.write(f"""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus augue nec tortor dignissim lobortis. Nam porta sollicitudin sodales. Maecenas nibh tellus, pretium eu odio facilisis, maximus malesuada tortor. Vestibulum id mauris vitae risus luctus fermentum et et nibh. Pellentesque volutpat enim magna, id tempus leo scelerisque in. Mauris mattis tristique lacus et elementum. Phasellus consectetur porta magna vel iaculis. Etiam a mattis nunc, ut porta risus. In venenatis fermentum ligula vel efficitur. Vivamus a molestie turpis. Integer maximus luctus lorem cursus tempus. Vestibulum erat libero, convallis ac dictum sed, porttitor non nisi. Praesent tempor tristique felis, vel consectetur nunc tincidunt quis. In dignissim urna non metus maximus suscipit. Morbi semper, sapien quis convallis vulputate, nibh purus consectetur erat, nec scelerisque metus ex quis sem. Donec tempus id sapien non ultricies.
Proin in volutpat lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et nibh lectus. Phasellus molestie nulla nec velit accumsan, ultricies gravida ante dictum. Nam commodo nibh vulputate enim pretium malesuada. Pellentesque et viverra metus. Mauris feugiat libero quis luctus semper. Suspendisse ac bibendum leo. Aliquam erat volutpat. Proin augue magna, suscipit id iaculis vel, rhoncus in ipsum. Nam rhoncus nulla sed mi iaculis sodales. Vestibulum aliquet feugiat quam, ut porta nisi interdum ut.
Integer sed nibh porttitor, semper turpis id, commodo urna. Sed quis nisi quis ligula fringilla vulputate. Suspendisse facilisis magna vel mi scelerisque, a rhoncus augue dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus tincidunt eros leo, vitae iaculis tellus consequat id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pulvinar, dolor sed egestas fringilla, risus ex scelerisque risus, id tincidunt orci est vitae mauris. Ut non lectus ac purus pulvinar condimentum. Fusce dapibus dolor iaculis, maximus erat a, finibus ante. Fusce in urna massa. Cras porttitor vitae quam eget auctor.
Nunc eget enim ut mi rhoncus pellentesque vitae id magna. Quisque et tempus diam. Morbi volutpat a tellus vel aliquet. Donec dolor libero, luctus quis ornare nec, sagittis eu dolor. Nulla vitae posuere sapien. Fusce porta sem neque, nec luctus velit eleifend volutpat. Sed posuere vestibulum erat a tempus. Morbi dapibus nec felis a tristique.
Vivamus mattis iaculis tincidunt. Nunc id justo sit amet sem sodales sollicitudin. Vivamus convallis, nunc ac commodo cursus, nisi nisi cursus enim, in fermentum augue massa ac ex. Quisque vitae justo purus. Proin accumsan semper commodo. Vestibulum ipsum turpis, rhoncus eu molestie a, ultricies at justo. Proin tincidunt sagittis quam nec tincidunt. Mauris sit amet purus vel diam iaculis dignissim sed et lorem.
Integer id mauris vel eros feugiat luctus. Integer at ante ornare arcu malesuada auctor. Donec varius luctus erat, quis imperdiet tortor pharetra quis. Aliquam dictum massa mauris, id interdum massa porttitor ut. Donec vitae iaculis lectus, sed molestie magna. Fusce ac est et urna dictum vehicula quis et eros. Donec ornare interdum massa sit amet malesuada. Donec in nibh quis metus feugiat rhoncus. Sed arcu urna, porttitor sed imperdiet a, tincidunt vel odio. Quisque egestas egestas orci dictum accumsan. Curabitur non risus ligula. Sed a nibh sagittis, eleifend neque quis, eleifend nibh. Proin sagittis ante ligula, ultrices tempor sem luctus ut. Aliquam auctor tincidunt nulla.
Etiam at ipsum convallis, porta nisi non, euismod magna. Maecenas porta congue leo id accumsan. Integer hendrerit lacinia tellus, et pulvinar metus blandit sit amet. Cras varius turpis lorem, eu suscipit lectus commodo imperdiet. Fusce leo nisi, pharetra et mauris eget, mattis blandit elit. Duis ac convallis nisi, sed tincidunt massa. Sed nec nulla at nisi venenatis placerat nec malesuada nunc. Suspendisse luctus augue eros, non feugiat lorem consectetur at. Nullam lobortis consectetur augue sit amet sodales.
Duis nisi augue, pharetra sit amet ultrices eu, lobortis nec erat. Nulla lacus dui, facilisis eu lorem et, vulputate sollicitudin nisi. Aenean semper nibh eget nulla vestibulum, non consequat tellus faucibus. Donec sit amet diam malesuada, facilisis ante quis, tincidunt arcu. Aliquam erat volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non lectus aliquet, bibendum arcu nec, eleifend lorem. Mauris nec eleifend metus. Sed eget dolor lacus. Quisque imperdiet efficitur vulputate. Vivamus malesuada tellus non nisi auctor tincidunt. Fusce at ipsum consectetur arcu interdum mattis.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vulputate et velit in posuere. Duis id lorem metus. Aenean lobortis egestas risus, nec euismod nisi ullamcorper at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus mauris lectus, laoreet bibendum risus nec, imperdiet aliquet augue. Proin ut libero luctus, feugiat ipsum non, hendrerit elit. Fusce eget quam aliquam, porta magna aliquam, euismod ligula. Nam vitae tellus mauris. Duis at tortor id risus dapibus scelerisque. Vestibulum eu ligula a nulla convallis feugiat a vitae tortor. Curabitur egestas libero sed felis dictum, nec scelerisque nibh imperdiet. Vivamus maximus lorem in dui facilisis, vel tincidunt purus posuere.
Vestibulum pharetra aliquet elit et mattis. In rutrum consequat felis, non hendrerit augue varius sed. In eu posuere magna. Sed dolor turpis, iaculis ac sollicitudin vitae, volutpat sed metus. Mauris pellentesque, lorem sit amet aliquam elementum, leo diam dignissim risus, eu dapibus neque nisl ac ligula. Maecenas mauris ligula, vestibulum sed malesuada et, pharetra sit amet est. Integer eget tellus odio.
Ut condimentum eget nulla in lacinia. Sed non hendrerit mi. Aliquam sed erat blandit, varius odio non, cursus tellus. Proin efficitur ligula nulla, et lacinia dolor euismod sit amet. Donec interdum lacus auctor pellentesque venenatis. Sed lectus purus, hendrerit eu leo sit amet, hendrerit fringilla libero. Nunc consectetur non enim vitae vehicula. Nunc rhoncus metus et porta auctor. Praesent sed tincidunt odio. Nullam nunc augue, tempor et justo in, placerat laoreet nisl. Morbi mattis eu neque vitae consectetur. Mauris facilisis, arcu a iaculis porttitor, leo ligula tristique erat, nec sodales sem nisl a eros. Curabitur ac nulla nec augue varius tincidunt id ut ipsum. Cras eros elit, vehicula eu sodales in, molestie sollicitudin tellus. Suspendisse interdum rhoncus nulla, vitae blandit lacus tempor eu.
Quisque vel ex vitae tellus vulputate eleifend eget ac lacus. Nullam scelerisque neque sed metus tincidunt molestie. Donec lacinia felis ipsum, molestie imperdiet metus tristique cursus. Phasellus pharetra, neque et varius tristique, lacus ex feugiat nibh, a mattis erat purus quis turpis. Aenean cursus hendrerit justo in iaculis. Donec in felis scelerisque, tristique libero ut, ornare lorem. Quisque posuere est a tortor interdum blandit. Donec quis tincidunt lectus, nec laoreet libero.
Quisque ultricies nibh at urna posuere, sed cursus sem sagittis. Ut rhoncus velit at risus viverra, et accumsan massa vulputate. Donec rutrum condimentum erat. Vestibulum iaculis nunc in turpis elementum, at aliquam augue dignissim. Nam dignissim arcu magna, ac placerat elit tincidunt eget. Fusce varius tristique felis, nec tristique ex aliquam ac. Nam pellentesque justo a mauris lacinia, sit amet viverra elit fringilla. Curabitur facilisis eget odio eget porta. Nam non nisi pellentesque, aliquet mauris sed, placerat tellus. Pellentesque dictum ligula turpis, vel luctus enim suscipit sit amet. Proin ultrices tellus sit amet eros lobortis, et mattis est commodo. Mauris lobortis placerat orci congue venenatis. Etiam vitae quam ullamcorper, ullamcorper dui ut, vestibulum lectus.
Curabitur consequat nisi dapibus, vestibulum nibh quis, pharetra lacus. Fusce consequat, velit nec pellentesque lacinia, mauris nunc mollis nibh, sed suscipit eros nulla ac justo. Aliquam gravida dolor massa, eget ornare erat pulvinar vel. Sed at mollis dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam sit amet laoreet turpis, sit amet condimentum magna. Donec feugiat leo imperdiet pretium finibus. Vivamus in magna sed ipsum tristique molestie. Ut scelerisque congue massa, non fringilla nibh sagittis a. Nulla lectus est, sodales ut vulputate non, efficitur eget nulla. Vivamus molestie commodo dui. Fusce vitae laoreet dui.
Cras luctus volutpat nulla vitae ornare. Sed sit amet tellus ex. Nunc ac tempus tellus. Aenean egestas ligula sit amet mollis ultricies. In euismod dolor vel felis euismod mollis. Aliquam eu lacus ut orci lacinia vestibulum vitae eget eros. Praesent vel orci nisi.
Nulla fermentum feugiat commodo. Morbi condimentum ut purus quis suscipit. Proin quis diam suscipit, mattis velit quis, tincidunt sapien. Duis et tristique felis. Aliquam molestie mi in pretium ullamcorper. Integer sed iaculis erat. Donec et ligula sodales, placerat eros sit amet, condimentum turpis. Integer a lacus est.
Cras id facilisis urna, ut sodales turpis. Ut vitae nisl in tellus porttitor sollicitudin a vel urna. Curabitur ultrices lacus quis pulvinar lobortis. Nunc magna tellus, fringilla eget dapibus ut, dapibus et tortor. Suspendisse fermentum sapien sit amet augue sodales pulvinar. Cras nulla lorem, viverra sit amet ultrices in, tristique sed elit. Cras fringilla scelerisque velit et viverra. Aliquam sollicitudin volutpat lobortis. Aenean consectetur non elit sed sollicitudin. In efficitur ornare ullamcorper. Integer at urna ante. Donec euismod tincidunt erat, vitae tristique mauris sollicitudin interdum. Phasellus non dolor quis nisi fringilla viverra non quis turpis. Curabitur condimentum malesuada tempor.
Phasellus mattis, augue sit amet condimentum fringilla, metus lorem aliquam diam, sit amet vehicula diam arcu id ante. In ornare pellentesque eros, lobortis feugiat lorem vulputate eu. Phasellus sit amet dolor pretium, pellentesque libero ut, vulputate nibh. Etiam imperdiet a purus in placerat. Donec bibendum mauris id erat tempus, in tristique leo consequat. Vivamus a est quis augue feugiat euismod eget sit amet ante. Curabitur pharetra ante elementum sapien iaculis, sed condimentum neque cursus. Cras metus ipsum, blandit eu hendrerit nec, mattis vel purus. Aliquam varius arcu massa, a molestie felis porttitor nec.
In commodo, leo scelerisque blandit viverra, sem turpis viverra libero, eget tincidunt diam neque id ante. Morbi velit tellus, laoreet ut imperdiet a, blandit vel velit. Etiam bibendum mattis purus ut fringilla. Sed sodales purus nisl, quis finibus metus pretium ac. Suspendisse pretium tincidunt lorem, eget posuere risus luctus ut. Quisque venenatis eleifend venenatis. Vestibulum in pharetra mi, a feugiat nulla. Nunc non posuere tortor. Aliquam erat volutpat. Mauris ornare turpis quis imperdiet rutrum. Nam auctor, erat id laoreet blandit, enim arcu tempus tellus, nec molestie libero purus ac est. Cras tristique vulputate congue.
Duis lacus turpis, hendrerit in dui et, euismod rutrum nisl. Aenean tristique molestie risus, in vestibulum ligula pellentesque ac. Duis et vehicula magna. Integer feugiat velit quis mollis dapibus. Sed ut lacus et erat rhoncus aliquet. Nulla facilisi. Quisque sit amet iaculis lectus, at iaculis enim. Sed scelerisque nisi et elementum facilisis. Suspendisse tincidunt felis sit amet consequat aliquam. Fusce non finibus nunc, vel tincidunt tortor. Sed dictum commodo consectetur.
Duis ut diam eget quam venenatis efficitur eu vel enim. Quisque tempus, justo eget fringilla lacinia, erat nulla eleifend ante, sagittis blandit odio nibh non ligula. Mauris pulvinar, erat convallis convallis ornare, purus augue efficitur nulla, ut ornare tortor arcu sit amet velit. Donec vel nunc fringilla, ultricies ante sit amet, accumsan mauris. Duis ultrices dignissim sem, non euismod neque facilisis nec. Donec dictum nunc non neque vestibulum luctus. Pellentesque tincidunt, enim at auctor feugiat, augue leo faucibus eros, eget consequat mauris justo sed diam. In nunc ante, volutpat vel diam sit amet, blandit scelerisque velit. Sed vel arcu id massa scelerisque ultrices malesuada sed est. Fusce non tortor in libero maximus semper. Ut venenatis metus sed ex porta, sit amet fringilla risus sagittis. Nam non arcu tortor. In sit amet tincidunt tortor, nec mollis dolor. Duis in dui vitae nisi luctus interdum.
Praesent at orci ut orci scelerisque pulvinar. Vivamus hendrerit lorem ipsum. Nullam ut tincidunt orci. Sed pulvinar lectus eu gravida mattis. Nulla congue turpis sed aliquet condimentum. Vestibulum aliquam mi id commodo aliquet. Nulla iaculis lacus nec orci consequat, sit amet sagittis magna porta. Curabitur viverra metus quis pharetra tincidunt. Nullam mattis fermentum risus, eget elementum risus iaculis vitae. In tincidunt est et velit dictum lacinia. Sed in neque ut justo luctus lacinia. Suspendisse sodales nisl turpis, sit amet elementum diam faucibus sed. Suspendisse at scelerisque magna. Morbi id interdum sapien.
Donec aliquam tempor fringilla. Nam augue est, posuere id pellentesque ut, hendrerit eu ex. Praesent vulputate mi nec ipsum tempus, et sagittis massa tincidunt. Ut congue nec urna non bibendum. Aliquam non tempus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse ac ipsum semper sapien commodo finibus eu sit amet magna. Donec elit tellus, dictum non ligula at, rhoncus pulvinar eros. Vestibulum faucibus erat massa, id tincidunt massa suscipit ac. Phasellus varius varius elit, a mollis velit. Pellentesque finibus, nisi non aliquam efficitur, risus enim scelerisque nisl, et auctor mi orci in est. Integer sed ipsum vel quam rhoncus gravida eget id dolor.
Sed pellentesque nulla et pellentesque convallis. Donec blandit, arcu eu consectetur fermentum, dolor libero lobortis mi, nec suscipit ex nisl nec lacus. Maecenas aliquet risus lobortis lacus varius, iaculis sodales massa hendrerit. Mauris et sapien sollicitudin, bibendum velit convallis, fringilla orci. Aenean velit risus, auctor non ultricies sed, suscipit et velit. Etiam aliquet nisl imperdiet erat egestas blandit. Proin id ligula aliquam, semper mi eu, egestas nisl. Aenean tincidunt porttitor sem et placerat. Nunc tincidunt nibh eros, eget euismod magna imperdiet ac. Praesent eleifend at ligula ut maximus. Phasellus tincidunt aliquam tincidunt.
Nullam dictum interdum magna id posuere. Mauris sollicitudin efficitur felis. Etiam imperdiet tortor non augue eleifend condimentum. Sed sed libero ac tellus sodales molestie. Quisque risus diam, vestibulum nec eros in, luctus auctor enim. Donec mattis magna in diam egestas, eget malesuada erat euismod. Aenean finibus auctor lorem non iaculis. Cras id pellentesque ipsum, sit amet porttitor metus. Nulla finibus vel leo vitae interdum. Donec in accumsan sapien, gravida venenatis tellus. Etiam sit amet semper leo. Aenean in nisl lectus. Sed sed eros aliquam mauris porta ultrices pulvinar quis mi. Aenean luctus lacus et neque iaculis eleifend. Vivamus ut tristique lacus, a ornare risus.
Vestibulum aliquet tincidunt velit, euismod tempor risus varius ac. Cras a augue eget risus auctor condimentum. Morbi ultricies et lorem in accumsan. Pellentesque pharetra at dolor at volutpat. Donec vel pellentesque tellus. Mauris sit amet justo ornare, tempus odio vel, suscipit augue. Duis venenatis tortor quis ante tristique, quis blandit magna semper.
Donec gravida purus velit, ut efficitur sapien convallis at. Pellentesque nec porta lorem, et bibendum metus. Donec convallis eros nunc, commodo posuere tellus consectetur in. Aenean quis viverra urna. Nam dapibus gravida pellentesque. Nam at sapien finibus, vulputate lacus eget, sollicitudin augue. Sed vitae urna sagittis, egestas lorem mollis, posuere purus. Curabitur mollis urna lacus, eget bibendum lectus convallis sed. In in leo in sapien tincidunt volutpat in et turpis. Nunc ac elit ut nisl viverra porttitor at sed purus.
Sed a venenatis orci. Aenean finibus nibh rhoncus nulla rutrum lobortis. Ut leo magna, dignissim id elit a, lacinia volutpat urna. Pellentesque ac leo faucibus neque faucibus euismod id sit amet nisl. Nullam et tellus vitae tellus mattis tincidunt at eget ligula. Quisque eget leo odio. Vivamus placerat ante ligula, ullamcorper convallis felis faucibus in. In laoreet turpis id diam malesuada porttitor. Nulla bibendum lorem nisl, eu facilisis mi tincidunt non. Cras sit amet eros ac eros condimentum convallis. Aenean ultricies elit nisl, vitae ultricies tortor sodales et. Sed blandit, velit ac ultricies pellentesque, velit augue hendrerit turpis, vel convallis lacus justo vitae sapien.
Nullam nibh metus, porta in metus at, convallis accumsan velit. In est sem, laoreet vel maximus quis, fringilla ut eros. Pellentesque scelerisque ligula vitae sapien pretium auctor sit amet eget urna. Fusce mattis vestibulum nulla a accumsan. Aenean consectetur neque at volutpat sagittis. Donec suscipit porttitor molestie. Aenean vel odio eget metus condimentum vulputate non a libero. Vestibulum vitae sodales diam. Sed dignissim congue mattis. Quisque suscipit elementum ligula, pellentesque dignissim metus congue eu. Phasellus at mattis arcu. Fusce dapibus efficitur nunc. Suspendisse malesuada venenatis facilisis. Praesent ultrices lobortis risus, vitae viverra odio euismod at. Nullam nulla mauris, cursus non condimentum sit amet, convallis sed velit. Proin porta, ipsum non ultrices porta, quam felis pretium eros, non ultricies turpis justo sit amet diam.
Aliquam lacinia, est semper pharetra lacinia, velit metus congue lorem, vel eleifend justo sem in quam. Nulla et interdum nibh. In urna dolor, blandit in massa vel, elementum lobortis mauris. Ut a risus risus. Duis eros erat, imperdiet sit amet mollis at, lacinia et diam. Donec tristique diam eget commodo suscipit. Proin dictum venenatis quam eleifend blandit. Cras et congue tortor. Ut in pulvinar felis. Cras quis velit fringilla, bibendum urna eu, egestas metus. Maecenas quis luctus ante, venenatis commodo neque. Donec sit amet pharetra ex. In nec augue quis enim rutrum placerat. Nullam congue ante turpis, et vestibulum purus tempus nec. Interdum et malesuada fames ac ante ipsum primis in faucibus.
Pellentesque egestas ante lorem, at egestas ex ornare pulvinar. Nullam dictum nisi vel risus tempus, eu suscipit velit blandit. Sed non velit dui. Nullam in nisl ante. Quisque in magna vel leo fringilla finibus ac eget sapien. Etiam blandit libero vitae sapien fermentum molestie. Fusce sapien tortor, mollis non mi eget, sodales molestie ligula. Donec in viverra metus, nec accumsan ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ultricies finibus nisl, at pharetra nisl tempus id. Nam id velit tincidunt diam posuere vehicula. Nullam ut facilisis velit. Vivamus pulvinar hendrerit sem, a sodales orci aliquam id. Sed velit mi, dignissim vehicula velit malesuada, gravida efficitur diam. Nulla ut blandit ante.
In nec ante pellentesque, ornare purus vitae, condimentum arcu. Maecenas in bibendum tortor, non aliquet orci. Aliquam feugiat varius erat, eu elementum ipsum accumsan at. Pellentesque dapibus maximus tincidunt. Praesent non vulputate nulla, in finibus justo. Praesent consequat vehicula eros. Donec finibus tempus ligula, a tincidunt tellus laoreet eget. Pellentesque rutrum eleifend sapien. Donec tincidunt dapibus felis, id lacinia lorem euismod eu. Etiam eget leo quis quam sollicitudin sollicitudin ac nec nulla. Sed vel neque rutrum, tristique nisi vitae, posuere mi.
Curabitur ultrices efficitur massa, eu consequat nisi mollis id. Nulla facilisi. Maecenas finibus nulla eu urna ultrices pretium. Integer lectus tellus, vestibulum quis sapien id, ultrices interdum erat. In lorem tellus, egestas ut tempor cursus, consequat faucibus risus. Aliquam ut mattis nulla. Vivamus congue at mi a rhoncus. Aliquam nec massa vitae quam posuere ultrices. Integer orci metus, elementum at varius id, pretium eu felis. Pellentesque luctus porttitor elit a facilisis. Vivamus non condimentum neque, sed posuere erat. Etiam nec nulla ex. Quisque sollicitudin varius ipsum, et iaculis enim venenatis vitae. Fusce egestas metus at lorem suscipit dignissim. Nam ligula massa, tempor eu placerat vel, blandit vitae turpis. Etiam elit enim, imperdiet at sem ac, venenatis hendrerit velit.
Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam odio metus, tincidunt eget lacus id, semper suscipit lorem. Quisque a lacus porta, blandit risus et, molestie tellus. In congue odio eu semper elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla eget mollis arcu. Suspendisse semper metus nibh, et tincidunt neque pharetra non.
Donec convallis finibus nisi. Praesent iaculis tristique convallis. Nulla at augue at quam luctus efficitur sed vitae nulla. Proin eget imperdiet mauris, consequat dapibus magna. Praesent laoreet magna metus, id tincidunt eros sollicitudin et. Duis nec sagittis elit. Sed vel varius dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas aliquet pellentesque lacinia. Vestibulum pretium luctus felis, sed pellentesque nunc porttitor non. Nam ullamcorper enim a quam feugiat convallis. Ut mi odio, tristique nec lorem eget, pretium tristique nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque ac nibh varius, lacinia dolor id, lacinia elit. Vivamus accumsan laoreet luctus. Nullam ultrices, dui eu faucibus vehicula, nisi enim eleifend ante, a blandit odio lacus id nulla.
In auctor hendrerit elit dignissim bibendum. {get_flag()} Aliquam sollicitudin posuere ligula vulputate pharetra. Sed fringilla mollis tellus ut pellentesque. Fusce molestie ex augue, vel euismod velit accumsan condimentum. Aliquam in eleifend erat. Aliquam interdum malesuada dolor nec pharetra. Etiam semper arcu tellus, id rhoncus dui posuere in. Cras diam ligula, pretium et erat vitae, auctor tristique nibh. Sed molestie, arcu at finibus fringilla, ipsum massa tristique nibh, a eleifend nisi urna a dolor. Nunc mattis mi eu placerat pretium. Nullam eget pellentesque massa, at condimentum neque. Maecenas pretium, dolor non dignissim mollis, justo ante faucibus ante, ut consequat purus arcu vitae elit. Nulla vestibulum sollicitudin sem. Curabitur ultrices felis magna, ac luctus lectus imperdiet vitae. Quisque imperdiet efficitur mi, sed congue est laoreet eget.
Suspendisse porttitor euismod urna a porta. Morbi tortor nulla, pretium et ex sit amet, sagittis eleifend tortor. Suspendisse eu enim imperdiet, gravida sem ut, iaculis libero. Sed eget enim eget est elementum aliquet. Aenean ullamcorper ex non laoreet condimentum. Proin vitae quam accumsan, gravida leo ut, auctor magna. Donec convallis mollis consectetur. Morbi condimentum finibus leo vitae viverra. Morbi fermentum, sem in accumsan cursus, ligula neque laoreet nunc, a vestibulum nisl augue pulvinar ante. Vivamus in lacinia nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eros augue, bibendum quis odio a, pretium sodales sem. Phasellus mi purus, aliquam vel luctus non, tincidunt quis sem. Pellentesque venenatis magna ac libero pulvinar efficitur.
Pellentesque vestibulum ultricies rutrum. Curabitur sit amet quam erat. In sed mi feugiat justo elementum semper sit amet et nisi. Duis non ipsum vitae erat posuere convallis eget eu risus. Nulla suscipit, felis eu facilisis maximus, massa nibh imperdiet sem, id pharetra neque ex non ante. Cras molestie tellus nibh, in eleifend massa mattis et. Nam rutrum nibh magna, nec consectetur ex efficitur ac. Nulla lacinia lacinia arcu sed feugiat. Maecenas volutpat arcu sagittis lacinia aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc nec magna eu arcu rhoncus congue. Vestibulum faucibus enim tortor, a condimentum nisl molestie ut.
Phasellus tincidunt sem ac tempor tempus. Quisque dui mi, rutrum eu condimentum et, tincidunt ut ante. Phasellus placerat, magna in facilisis congue, nisl enim interdum lorem, a elementum elit purus quis odio. Aenean semper arcu nec aliquet commodo. Integer posuere imperdiet tellus, semper interdum mauris finibus a. Aenean id vehicula neque, ac egestas lectus. Morbi placerat velit tellus, sed volutpat odio facilisis tempus. Integer quam nunc, varius et nisl quis, convallis pharetra neque. Cras ultricies et tellus vel fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce euismod rutrum aliquet. Nunc et dapibus mauris. Curabitur accumsan, sem vel venenatis commodo, purus nisl feugiat sem, id blandit lorem tellus a lacus. Suspendisse potenti.
Quisque at efficitur felis, eget rutrum lectus. Phasellus massa elit, semper non diam vehicula, mollis maximus eros. Mauris lacinia, lorem at ornare aliquam, purus nibh scelerisque ante, eu rutrum libero ligula ut enim. Etiam libero ipsum, facilisis non eleifend non, venenatis vel ipsum. Pellentesque risus arcu, ullamcorper et lectus vel, convallis sagittis sapien. In sed ex euismod, sollicitudin lacus quis, imperdiet enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tincidunt sem eu ante imperdiet, vel tristique ligula pharetra. Suspendisse ac nunc eget orci suscipit rhoncus.
Cras feugiat nulla lectus, eget aliquet est gravida quis. Aliquam ut finibus tellus, id interdum velit. Pellentesque volutpat malesuada tellus id malesuada. Vivamus justo felis, dictum eget suscipit in, pulvinar euismod justo. Vestibulum condimentum nisl lacus, vitae feugiat magna sollicitudin vel. Suspendisse non nisi nec nunc rhoncus tristique. Donec a nulla sed sem imperdiet fermentum. Ut ullamcorper lorem in gravida volutpat. Curabitur sit amet molestie elit, sed semper enim. Duis accumsan velit ante, ut elementum velit porttitor dignissim. Vestibulum elementum varius nulla molestie auctor. Aliquam eget risus volutpat, scelerisque lacus sit amet, dictum purus. Suspendisse aliquam egestas lectus, eget pellentesque quam iaculis nec. Sed condimentum, quam eget cursus interdum, orci est dictum nulla, eu cursus elit ligula vitae urna. Duis arcu turpis, scelerisque lacinia velit condimentum, auctor egestas lorem. Nulla facilisi.
Integer eget auctor ante. Sed lobortis in nisi sed convallis. Vestibulum iaculis accumsan velit id vestibulum. Nam vel venenatis lacus, quis fringilla augue. Sed ultrices sodales dui at ultrices. Donec eu pharetra felis. Maecenas in nunc non justo gravida elementum. Vestibulum convallis cursus nisi id elementum. Nunc in tempor erat.
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut dictum ultrices diam, interdum condimentum urna eleifend id. Phasellus vel accumsan odio, sed ultrices ex. Phasellus vulputate nisl a lectus venenatis condimentum. Cras dui enim, placerat malesuada cursus dictum, mollis imperdiet turpis. Proin quis nulla sem. Vestibulum ut est vehicula, volutpat odio at, cursus libero. Duis neque purus, sollicitudin nec enim ac, bibendum congue lectus.
Suspendisse bibendum metus a nisl blandit sodales. Nulla risus tortor, pharetra in congue fermentum, dapibus sed mauris. Nullam tincidunt, elit in tempus hendrerit, nisl purus dictum ante, et viverra orci lorem non lacus. Donec imperdiet, eros vel mattis commodo, neque nunc placerat magna, nec placerat nisl justo porta tortor. Nulla libero erat, faucibus eget sagittis ut, facilisis in augue. Sed tincidunt viverra nisl, vitae imperdiet massa scelerisque quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas a ultricies massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec ac odio id purus feugiat aliquet eu at elit. Nulla finibus metus orci, tempus ornare metus mollis nec.
Donec porttitor purus aliquam nulla pulvinar, non faucibus nisl vestibulum. Vivamus libero tortor, varius in augue vitae, tincidunt dignissim lorem. Curabitur pretium tincidunt vehicula. Duis at tortor mollis, convallis elit pellentesque, tempus metus. Donec porttitor pellentesque felis, ut fermentum enim euismod sit amet. Integer iaculis iaculis ligula sed lobortis. Maecenas eu nisi congue dolor tristique cursus feugiat ut velit. Sed eu aliquet ligula.
Nam id hendrerit ligula. Sed sed massa vehicula, faucibus elit vitae, porta lacus. Pellentesque sit amet bibendum lorem, sed egestas ligula. Sed vehicula mattis dapibus. Aenean mollis turpis felis, nec finibus purus volutpat ut. Maecenas maximus nunc odio, at mollis turpis feugiat eu. Aliquam quis est in dui gravida tincidunt at sit amet nunc. Vestibulum nec velit efficitur massa ullamcorper maximus. Sed scelerisque risus vehicula pellentesque viverra. Cras lectus turpis, iaculis vel mauris id, fringilla egestas nulla. Curabitur vulputate leo ac nisi consequat commodo. Sed dictum egestas ipsum eget aliquet.
Vestibulum consectetur nisl odio, ac tristique ex faucibus sed. Maecenas eget ex eu est condimentum gravida. Sed rhoncus tempor ultricies. Ut vel quam in est pulvinar viverra a vel metus. Fusce eleifend ex neque, id egestas tortor lacinia nec. Nulla ac porta metus, sit amet scelerisque augue. Nulla facilisi. Aenean interdum quam vitae nulla pulvinar, gravida pulvinar elit sollicitudin. Vivamus id nisi a augue elementum faucibus id vel ligula. Cras eget ornare leo, id luctus augue. Quisque fermentum magna quis tortor dictum mollis. Nam nunc odio, lobortis vel odio vitae, mollis consectetur lorem. Fusce at rutrum purus. Donec non vestibulum dolor. Etiam porttitor diam est, ut laoreet augue lacinia at. Phasellus pulvinar magna eu nisi posuere, ac ullamcorper metus egestas.
Nulla tempor faucibus lectus, in tempor magna. Nam lectus dolor, scelerisque eget hendrerit pulvinar, convallis vehicula lacus. Praesent ultricies lectus vitae mi dapibus scelerisque. Nam rutrum molestie orci. Nunc efficitur tristique maximus. Nulla fringilla, neque et vehicula gravida, mi nisl pulvinar tellus, vel molestie lectus augue at eros. Nulla non tellus rutrum, tincidunt justo at, accumsan ex. In feugiat nisi sed ante ultrices, at lacinia neque fermentum. Morbi eget maximus turpis. Sed et massa id odio dictum pulvinar id vel mauris. In id molestie sem, vitae vehicula nunc. Nullam eros metus, ornare vel odio nec, fringilla suscipit dolor. Nulla dignissim eros vel turpis bibendum interdum. Etiam et lectus eget tellus placerat elementum.
In hac habitasse platea dictumst. Mauris vel laoreet lacus. Fusce et nibh in purus pretium convallis ut vitae turpis. Duis lobortis, leo at ornare hendrerit, nibh ante malesuada dolor, et varius nisi nulla sit amet est. Nam maximus, odio sit amet iaculis tincidunt, augue erat rhoncus dolor, sed elementum justo orci a elit. Nulla ultricies nunc et mollis tincidunt. Vivamus semper dictum ante in porta. Phasellus vitae nulla dolor. In pharetra erat neque. Nulla felis nisl, lobortis nec suscipit ac, rutrum sed sem. Cras tincidunt elementum elit, pellentesque dignissim velit luctus vel.
Ut rhoncus, ipsum eget bibendum rutrum, odio nisi mattis sem, vitae scelerisque magna magna porttitor mi. Aliquam ac massa sed magna suscipit dictum id a ligula. Phasellus ante elit, cursus id mattis a, ultricies vel risus. Vivamus congue faucibus purus, et varius dui ornare eget. Morbi lobortis vehicula leo id pretium. Mauris quis faucibus nibh. Nam a augue a dui suscipit blandit. Aenean nec nisi ipsum. Nunc at leo neque. Phasellus interdum imperdiet accumsan.
        """)

def print_instructions():
    print("""
    In this challenge you will use the "grep" command to find the flag within a file
    that contains a lot of text. Here is an example of using "grep" to find text within a file:
        grep 'pwn.college' /tmp/searchme

    This command searches for the string 'pwn.college' within the file '/tmp/searchme'.
    Once you've found the flag within /tmp/searchme, you can submit it right away, no need
    to run this program again.
    """)

def get_flag():
    try:
        with open("/flag", "r") as f:
            return f.read()
    except FileNotFoundError:
        print("Error: Flag file not found.")

def main():
    print_instructions()
    setup()

if __name__ == '__main__':
    main()
